// =====================================================
// PDF EXPORT UTILITY
// Generate formatted PDF exports for registrations
// =====================================================

/**
 * Generate a PDF for registration submissions
 * Uses jsPDF library
 */
export async function exportToPdf(registration, submissions, options = {}) {
    // Dynamically import jsPDF to avoid SSR issues
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF({
        orientation: options.orientation || 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    // Colors
    const primaryColor = [99, 102, 241]; // Purple
    const textColor = [31, 41, 55]; // Dark gray
    const mutedColor = [107, 114, 128]; // Gray

    // Header
    doc.setFillColor(...primaryColor);
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Logo/Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('RegOS', margin, 25);

    // Registration title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(registration.title || 'Registration Export', margin, 33);

    // Export date
    doc.setFontSize(10);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - margin - 50, 25);

    // Reset text color
    doc.setTextColor(...textColor);

    // Registration Info
    let yPos = 55;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Registration Details', margin, yPos);
    yPos += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...mutedColor);

    const details = [
        `Category: ${registration.category || 'N/A'}`,
        `Status: ${registration.status || 'N/A'}`,
        `Total Submissions: ${submissions.length}`,
        `Views: ${registration.viewCount || 0}`,
    ];

    details.forEach(detail => {
        doc.text(detail, margin, yPos);
        yPos += 5;
    });

    yPos += 10;

    // Submissions Table
    if (submissions.length > 0) {
        doc.setTextColor(...textColor);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Submissions', margin, yPos);
        yPos += 5;

        // Get form fields for headers
        const formFields = registration.formSchema || [];
        const headers = ['#', 'Status', 'Submitted', ...formFields.map(f => f.label)];

        // Build table data
        const tableData = submissions.map((sub, index) => {
            const row = [
                index + 1,
                sub.status || 'pending',
                new Date(sub.submittedAt).toLocaleDateString(),
            ];

            formFields.forEach(field => {
                row.push(sub.formData?.[field.id] || '-');
            });

            return row;
        });

        // Generate table
        autoTable(doc, {
            startY: yPos,
            head: [headers],
            body: tableData,
            margin: { left: margin, right: margin },
            styles: {
                fontSize: 8,
                cellPadding: 3,
            },
            headStyles: {
                fillColor: primaryColor,
                textColor: [255, 255, 255],
                fontStyle: 'bold',
            },
            alternateRowStyles: {
                fillColor: [249, 250, 251],
            },
            columnStyles: {
                0: { cellWidth: 10 },
                1: { cellWidth: 20 },
                2: { cellWidth: 25 },
            },
        });
    }

    // Footer on all pages
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(...mutedColor);
        doc.text(
            `Page ${i} of ${totalPages}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
        );
        doc.text(
            'Generated by RegOS',
            margin,
            pageHeight - 10
        );
    }

    // Save or return
    const filename = `${registration.title || 'export'}_${Date.now()}.pdf`;

    if (options.returnBlob) {
        return doc.output('blob');
    }

    doc.save(filename);
    return filename;
}

/**
 * Generate a simple PDF report
 */
export async function generateReport(title, data, columns) {
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF();
    const margin = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, 25);

    // Date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, 32);

    // Table
    autoTable(doc, {
        startY: 40,
        head: [columns],
        body: data,
        margin: { left: margin, right: margin },
        styles: {
            fontSize: 9,
            cellPadding: 4,
        },
        headStyles: {
            fillColor: [99, 102, 241],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
    });

    const filename = `${title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
    doc.save(filename);
    return filename;
}
